namespace: "#{Kubernetes.Namespace}"
resources:
  - ../base
images:
  - name: shipped23
    newName: #{Octopus.Action.Package[shipped23].PackageId}
    newTag: #{Octopus.Action.Package[shipped23].PackageVersion}
