apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipped23-deployment
  labels:
    app: shipped23
spec:
  selector:
    matchLabels:
      app: shipped23
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shipped23
    spec:
      containers:
        - name: shipped23
          image: shipped23:latest
          ports:
            - containerPort: 8080
